name: Deploy to Production

on:
  push:
    branches:
      - main # Le workflow se déclenche uniquement sur la branche main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: SSH and deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /var/www/mon-app
          git pull origin main
          # Ajouter ici d'autres commandes de déploiement, par exemple :
          # npm install
          # pm2 restart mon-app
          # sudo systemctl restart mon-app.service
